### ISSUE TITLE
Note to Pro*COB documentation

### ISSUE THREAD

**Issue by GitMensch** [tiian/lixa#11]
Just checked the doc which mentions:

```sh
export COB_LDFLAGS=-Wl,--no-as-needed
tiian@ubuntu1404-64:/tmp$ cobc -x $(lixa-config -f -l) \
> -L/opt/oracle/instantclient_12_1 -lclntsh -lnnz12 \
> EXAMPLE2_ORA.cob \
> /opt/oracle/instantclient_12_1/cobsqlintf.o
```

I'd suggest to use the following instead:

```sh
cobc -x $(lixa-config -f -l) -L $ORACLE_HOME/lib $ORACLE_HOME/lib/cobsqlintf.o -lclntsh -Q "-Wl,--no-as-needed"
```

Explanations:

* I _guess_ something like `ORACLE_HOME` may be available also in your setup? If it isn't then I'd suggest to set a single environment variable and use this.
* libclntsh has a link itself to the correct libnnz version
* `-Q` allows you to pass anything to the linker (GC2+ feature, if I remember correctly) and `COB_LDFLAGS` can override some flags (if you want to use it for GC1 compat is likely best to export it as `export COB_LDFLAGS=-Wl,--no-as-needed $(cobc --info | grep COB_LDFLAGS | cut -d: -f2)` - and possibly don't export them but set it inline - only for the single  `cobc` invocation) 

Additional: one _may_ wants to use `-Q "-Wl,-R $ORACLE_HOME/lib"` as this removes the need to setup LD_LIBRARY_PATH to run the example.

**Comment by GitMensch** [comment]
@tiian There is no mention of the oracle libraries in the README, could you please adjust it (I _guess_ it would be an optional dependency)?

**Comment by tiian** [comment]
> * I _guess_ something like `ORACLE_HOME` may be available also in your setup? If it isn't then I'd suggest to set a single environment variable and use this.

Agree.

**Comment by tiian** [comment]
> * ibclntsh has a link itself to the correct libnnz version

You're right, for some historical reason I battled a lot with the version number of that library, will remove in the example

**Comment by tiian** [comment]
> * `-Q` allows you to pass anything to the linker (GC2+ feature, if I remember correctly) and `COB_LDFLAGS` can override some flags (if you want to use it for GC1 compat is likely best to export it as `export COB_LDFLAGS=-Wl,--no-as-needed $(cobc --info | grep COB_LDFLAGS | cut -d: -f2)` - and possibly don't export them but set it inline - only for the single  `cobc` invocation)

I'll add it as an hint, but it does not work with the very old versions shipped with old Linux distribution

**Comment by tiian** [comment]
> @tiian There is no mention of the oracle libraries in the README, could you please adjust it (I _guess_ it would be an optional dependency)?

They are explained in the annex of the reference manual in the section dedicated to Oracle DB set-up. Anyway I'll put a generic dependency statement in the README as well.

**Comment by tiian** [comment]
Documentation refined according to the suggestions.

**Comment by GitMensch** [comment]
> Documentation refined according to the suggestions.

Yay. ven solved before getting one year old ;-)

> > * `-Q` allows you to pass anything to the linker (GC2+ feature, if I remember correctly) and `COB_LDFLAGS` can override some flags (if you want to use it for GC1 compat is likely best to export it as `export COB_LDFLAGS=-Wl,--no-as-needed $(cobc --info | grep COB_LDFLAGS | cut -d: -f2)` - and possibly don't export them but set it inline - only for the single  `cobc` invocation)
> 
> I'll add it as an hint, but it does not work with the very old versions shipped with old Linux distribution

Which Linux distro has such an outdated version of GnuCOBOL? Would this version be relevant to lixa, given it possibly may not have even support?
This is a _real_ question.

Side question to 7805e9c38aa02d2c6504049ed4f65a38a4385b24: Is increasing copyright years the correct thing to do when there was no change to the files other than this (changing the year is not a copyrightable change itself, is it)?

If not you may want to take it out of that commit and force-push.
