### ISSUE TITLE
Build failure of 1.9.2 on Ubuntu 20.04

### ISSUE THREAD

**Issue by rowland66** [tiian/lixa#7]
I have installed the release tagged 1.9.2 from GitHub on Ubuntu 20.04 and configured with --disable-xta-java and --disable-xta-python

When I run make, I get the following compilation error, that appear to be related to dependencies. :

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../.. -I../../../src/client -I../../../src/xta -I../../../src/common -I../../../src/client -I../../../src/xta -D_TRACE -I/usr/include/libxml2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wall -fno-strict-aliasing -g -O2 -MT liblixtapp_la-Xta.lo -MD -MP -MF .deps/liblixtapp_la-Xta.Tpo -c Xta.cpp  -fPIC -DPIC -o .libs/liblixtapp_la-Xta.o
In file included from Xta.hpp:30,
                 from Xta.cpp:30:
MysqlXaResource.hpp:49:30: error: expected ')' before '*' token
   49 |         MysqlXaResource(MYSQL *connection, std::string const& name,
      |                        ~     ^~
      |                              )
MysqlXaResource.hpp:62:9: error: 'xta_mysql_xa_resource_t' does not name a type; did you mean 'xta_native_xa_resource_t'?
   62 |         xta_mysql_xa_resource_t *mxar;
      |         ^~~~~~~~~~~~~~~~~~~~~~~
      |         xta_native_xa_resource_t
MysqlXaResource.hpp: In member function 'virtual xta_xa_resource_t* xta::MysqlXaResource::getCBaseXaResource()':
MysqlXaResource.hpp:56:41: error: 'mxar' was not declared in this scope
   56 |             return (xta_xa_resource_t *)mxar; }
      |                                         ^~~~
In file included from Xta.hpp:31,
                 from Xta.cpp:30:
PostgresqlXaResource.hpp: At global scope:
PostgresqlXaResource.hpp:48:36: error: expected ')' before '*' token
   48 |         PostgresqlXaResource(PGconn *connection, std::string const& name,
      |                             ~      ^~
      |                                    )
PostgresqlXaResource.hpp:61:9: error: 'xta_postgresql_xa_resource_t' does not name a type; did you mean 'xta_native_xa_resource_t'?
   61 |         xta_postgresql_xa_resource_t *pxar;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         xta_native_xa_resource_t
PostgresqlXaResource.hpp: In member function 'virtual xta_xa_resource_t* xta::PostgresqlXaResource::getCBaseXaResource()':
PostgresqlXaResource.hpp:55:41: error: 'pxar' was not declared in this scope
   55 |             return (xta_xa_resource_t *)pxar; }
      |                                         ^~~~

**Comment by tiian** [comment]
The same bug has been reproduced even in Ubuntu 14.04, default build environment; it's not related to the Ubuntu version, but to the --disable-xta-java --disable-xta-python together. I have to fix the build procedure for this configuration.

**Comment by rowland66** [comment]
I was able to work around the error by adding --disable-xta-cpp.

**Comment by tiian** [comment]
XTA for C++ requires both MySQL(or MariaDB) and PostgreSQL because the two classes are statically generated.
The proper configuration options are:

./configure --disable-xta-java --disable-xta-python --with-mysql --with-postgresql

I will try to force the latest two when C++ is not disabled (the workaround you discovered by yourself).

**Comment by tiian** [comment]
Commit 38a036faeddf29b00ff448a75919354045369595 protect against the misconfiguration:

./configure --disable-xta-java --disable-xta-python
...
configure: error: XTA for C++ requires --with-mysql and --with-postgresql

./configure --disable-xta-java --disable-xta-python --with-mysql --with-postgresql
...
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing tests/atconfig commands

I think this issue can be closed.
