### ISSUE TITLE
Coping with XA inconsistency during commits

### ISSUE THREAD

**Issue by LWilkinson-LzLabs** [tiian/lixa#9]
This is (hopefully) the start of a discussion...
There are potential race issues with XA multi-RM commits, where an early commit can trigger an action which starts before later commits have completed. This is mentioned here, along with possible remedies: http://jbossts.blogspot.com/2011/04/messagingdatabase-race-conditions.html
We have this problem with transactions that update a database, and generate a follow-on message. In some cases this message can be processed before the database updates are visible to it.
As we are not in a position to modify the transaction processing programs our existing (non-LIXA) fix/workaround is to guarantee that the message commit is the last one to happen. Another possibility is to prevent any new transactions starting during the Commit sequence, but this is rather drastic.
Would it make sense to add some (optional) explicit commit ordering to the RMs within LIXA?

**Comment by tiian** [comment]
This is a well known behavior I have already met with commercial enterprise software and using LIXA in comparison with other transaction managers may help, but not completely solve the race condition described in the linked article.

Statement: LIXA library calls XA methods sequentially and using the same order of the resource managers id: if you put 3 resource manager in some order in a profile, LIXA library will call xa_prepare and xa_commit in the same exact order. If you want your messaging system receive xa_commit as the last participant, specify your messaging system as the last resource manager in a LIXA profile.
You can observe the behavior activating the corresponding trace flag.

But, there's a "but" that neither LIXA nor any other transaction manager can solve...
XA specification states: "_A transaction manager calls xa_commit() to commit the work associated with ∗xid. Any changes made to resources held during the transaction branch are made permanent. [...]_"
What does it really mean "are made permanent" for a sophisticated relational database? Is it the exact meaning of "are consistent for an immediate subsequent read from another client"?... Obviously no.
If the resource manager reply XA_OK to xa_commit() and asynchronously does some further step before data are accessible to a subsequent read, there's a chance a message triggered by the same transaction reaches its destination recipient before the database completed its asynchronous internal job.
In my professional life I experienced it with a Java application server sending a message to a COBOL TP monitor: it seemed impossible, but it happened few times every some hundred thousands transactions. The most practical solution was: if SELECT returns no row, retry it one second later for a maximum number of times (5).

Stated all the above, be sure it really happens in production before trying to solve it.
If you really met the race condition, try to work on the resource manager side if some parameter can guarantee a full synchronous xa_commit after an xa_prepare.

**Comment by tiian** [comment]
Does the above reply answer your question? Can the issue be closed?

**Comment by LWilkinson-LzLabs** [comment]
If the documentation can define that the commit order is always the RM order as specified in the lixac_conf, I think that would be a reasonable solution.

**Comment by tiian** [comment]
Commit 0cd0212a6cbe9c92a05f38a802828d5cc0400f13 improve documentation.
